version: "3"
services:
  db:
    image: postgres:14.0
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  web:
    build: .
    command: bash
    environment:
      PORT: "4000"
    volumes:
      - .:/apps
    working_dir: /apps
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true